### ISSUE TITLE
Fails with "drmModeGetResources failed: Invalid argument" with NVIDIA proprietary drivers on Ubuntu 18.04

### ISSUE THREAD

**Issue by cirosantilli** [robclark/kmscube#12]
NVIDIA Quadro M1200 Mobile, Ubuntu 18.04 nvidia-384 driver, kmscube 56c3917ffd1f05942246e2532ca4a5707554a2fc , go to Crtr + Alt + 3 TTY, run `kmscube`, fails with:

    drmModeGetResources failed: Invalid argument
    failed to initialize legacy DRM 

Same on 98f31bfaf61f2cfb01ff747ae91f2b3bc7564ce6 from https://gitlab.freedesktop.org/mesa/kmscube

**Comment by robclark** [comment]
I'm not really sure if kmscube is expected to work w/ nv blob driver (that is probably an issue to file against nv blob driver).. but either way, upstream for kmscube has moved to:

https://gitlab.freedesktop.org/mesa/kmscube

**Comment by cirosantilli** [comment]
@robclark thanks, can you point to that gitlab repo on the description of this repo? Since this is the first google hit.

**Comment by robclark** [comment]
good idea, done
